name: huawei_hmsavailability_example
description: Demonstrates how to use the Huawei Hmsavailability Plugin.

environment:
  sdk: ^3.5.0
  flutter: ^3.24.3

dependencies:
  flutter:
    sdk: flutter
  huawei_hmsavailability:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
