name: huawei_location_example
description: Demonstrates how to use the Huawei Location plugin.

environment:
  sdk: ^3.5.0
  flutter: ^3.24.3

dependencies:
  flutter:
    sdk: flutter
  huawei_location:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
